### ISSUE TITLE
some synax from specification can't parse

### ISSUE THREAD

**Issue by TsuITOAR** [domodwyer/fastxdr#12]
these examples are from [xdr specification](https://datatracker.ietf.org/doc/html/rfc4506), and `fastxdr` will throw `ParsingError`   
enum:
```
enum { RED = 2, YELLOW = 3, BLUE = 5 } colors;
```
option data where `*` prefix the ident
```
struct stringentry {
           string item<>;
           stringentry *next;
        };
typedef stringentry *stringlist;
```
this from [port mapper spec](https://datatracker.ietf.org/doc/html/rfc1833#section-3.1)
```
struct *pmaplist {
    mapping map;
    pmaplist next;
};
```

**Comment by TsuITOAR** [comment]
seems enum works, but there is a zero width space `\u{200b}` from the spec page code and cause `parse error`, this works
```
enum Color{RED=0,YELLOW=1};
```
and there are some synax shows a lot but not defined by xdr spec , I find some from [vxi11 spec](http://www.vxibus.org/specifications.html)
define enum ellipsis constants
```
enum Device_AddrFamily { 
    DEVICE_TCP,
    DEVICE_UDP
};
```
unsigned char, unsigned int, and unsigned long, seems they are all 4-bytes wide, just like (unsigned) int.
```
struct Create_LinkResp {
   Device_ErrorCode error;
   Device_Link lid;
   unsigned short abortPort; /* for the abort RPC */
   unsigned long maxRecvSize; /* specifies max data size in bytes
   device will accept on a write */
};
```
```
struct Device_ReadStbResp {
   Device_ErrorCode error; /* error code */
   unsigned char stb; /* the returned status byte */
};
```
It would be great if you can add some support for them.

**Comment by domodwyer** [comment]
Hi @TsuITOAR 

These types do not appear in the [XDR specification](https://datatracker.ietf.org/doc/html/rfc1014).

I would have suggested making a tyepdef, but identifiers are defined as:

```
   (3) An identifier is a letter followed by an optional sequence of
   letters, digits or underbar ('_'). The case of identifiers is not
   ignored.
```

And therefore something like:

```
typedef unsigned int unsigned short;
```

Will not work, as `unsigned short` is not a valid identifier because it contains a space and the above statement is ambiguous when parsed.

Therefore you can either:

* Simply change your spec to use `unsigned int` instead of `unsigned short`....
or
* Add the types to fastxdr internally so it can recognise them and treat them as the appropriate types. 

> It would be great if you can add some support for them.

If you want support for this non-standard feature, you will need to add it yourself - please PR back your changes to share with others.

**Comment by TsuITOAR** [comment]
> Hi @TsuITOAR
> 
> These types do not appear in the [XDR specification](https://datatracker.ietf.org/doc/html/rfc1014).
> 
> I would have suggested making a tyepdef, but identifiers are defined as:
> 
> ```
>    (3) An identifier is a letter followed by an optional sequence of
>    letters, digits or underbar ('_'). The case of identifiers is not
>    ignored.
> ```
> 
> And therefore something like:
> 
> ```
> typedef unsigned int unsigned short;
> ```
> 
> Will not work, as `unsigned short` is not a valid identifier because it contains a space and the above statement is ambiguous when parsed.
> 
> Therefore you can either:
> 
> * Simply change your spec to use `unsigned int` instead of `unsigned short`....
>   or
> * Add the types to fastxdr internally so it can recognise them and treat them as the appropriate types.
> 
> > It would be great if you can add some support for them.
> 
> If you want support for this non-standard feature, you will need to add it yourself - please PR back your changes to share with others.

the optional type def need some fix, which is from the xdr spec
```
struct stringentry {
           string item<>;
           stringentry *next;
        };
typedef stringentry *stringlist;
```

```
struct *pmaplist {
    mapping map;
    pmaplist next;
};
```
